# Node.js

trigger:
- develop

pool:
  vmImage: ubuntu-latest

steps:
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy files'
- task: NodeTool@0
  inputs:
    versionSpec: '18.16.1'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'
- script: |
    npm run start-dev
  displayName: 'npm build'
  
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'freelunch-api' 
