# Node.js

trigger:
- develop

pool:
  vmImage: ubuntu-latest

steps:

- task: NodeTool@0
  inputs:
    versionSpec: '18.16.1'
  displayName: 'Install Node.js'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy files'
  
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'freelunch-api' 
  displayName: 'Publish npm artifact'

- script:
    ls $(Build.ArtifactStagingDirectory)
  displayName: 'testing'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'FreeLunchFantasySubscription(e2d91e5f-7659-43aa-bffc-22aed71fcb48)'
    appType: 'webAppLinux'
    WebAppName: 'freelunch-api'
    package: '$(Build.ArtifactStagingDirectory)/**/*.*'
    RuntimeStack: 'NODE|18-lts'
    StartupCommand: 'pm2 start ecosystem.config.cjs'